# Generated by Django 5.2.7 on 2025-10-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobupdate',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, db_column='timestamp'),
        ),
    ]
